### ISSUE TITLE
Can't install using melpa: "No such file or directory, cus-edit"

### ISSUE THREAD

**Issue by solace-rcampbell** [renzmann/treesit-auto#45] opened 2023-05-18 13:29 UTC
I'm trying to install treesit-auto using a snap version of emacs "GNU Emacs 29.0.90".

When I run the melpa instructions I get this error:
`package--save-selected-packages: Cannot open load file: No such file or directory, cus-edit`

**Comment by solace-rcampbell** [comment] 2023-05-24 00:11
Is this a problem with treesit-auto, or is this a problem with the emacs snap?

**Comment by renzmann** [comment] 2023-06-23 20:02
Sorry, I don't really know anything about Snaps or how they might affect the Emacs installation.  I can noodle around and see if this error ever comes up for me too, but I can't say I'm able to reproduce it right now

**Comment by jcs090218** [comment] 2023-06-23 20:27
It seems like `cus-edit` is built-in to Emacs. See https://github.com/emacs-mirror/emacs/blob/master/lisp/cus-edit.el.

Try upgrade the Emacs snapshot. The latest version is `29.0.92`.

**Comment by solace-rcampbell** [comment] 2023-06-26 13:28
OK.  I tried upgrading to a newer snap, and that problem went away (I was able to install treesit-auto), but none of the M-x functions seem available.

For example, after a successful install, `M-x treesit-auto-install-all` gives `[no match]`.

**Comment by solace-rcampbell** [comment] 2023-06-26 13:30
And if I type `M-x treesit-` and hit tab, `auto` is not in the list of completion options.

**Comment by renzmann** [comment] 2023-11-11 02:32
I haven't seen any other reports of this, and can't reproduce, so I'm going to close this for now.

**Closed** 2023-11-11 02:31 UTC
